language: generic
sudo: required
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run notes bundle exec rails db:test:prepare
script:
- docker-compose run --rm notes bundle exec rake spec
after_success:
- echo $HEROKU_TOKEN | docker login -u _ --password-stdin registry.heroku.com
- docker build -t registry.heroku.com/bw-gwi-docker/web -f Dockerfile.production .
- docker push registry.heroku.com/bw-gwi-docker/web
- heroku run --app bw-gwi-docker bundle exec rails db:migrate
before_install:
- openssl aes-256-cbc -K $encrypted_07d74bfc0e91_key -iv $encrypted_07d74bfc0e91_iv
  -in .heroku-netrc.enc -out .heroku-netrc -d
- cat .heroku-netrc >> $HOME/.netrc
