language: generic
sudo: required
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run notes bundle exec rails db:test:prepare
script:
- docker-compose run --rm notes bundle exec rake spec
after_success:
  # for local testing, needs to be set on travis, too:
  # export HEROKU_TOKEN=$(heroku auth:token)
- docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
- docker build -t registry.heroku.com/docker-travis-heroku/web -f Dockerfile.production .
- docker push registry.heroku.com/docker-travis-heroku/web
- heroku run bundle exec rails db:migrate
